# !! File must end with empty line !!
dependencies:
  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: jx3-aws-spring-boot-gradle-app
  repository: file://../jx3-aws-spring-boot-gradle-app
